- name: Configure and Build iPXE
  gather_facts: false
  hosts: all
  vars:
    ipxe_files:
      - /ipxe-debug.lkrn
      - /ipxe-debug.pxe
      - /ipxe.lkrn
      - /ipxe.pxe
      - /undionly-debug.kpxe
      - /undionly.kpxe
    syslinux_files:
      - /menu.c32
      - /pxelinux.0
    pkgs:
      - syslinux-common
      - atftpd
  tasks:
# Normally I would _always_ use a module vs a command
# Since we are doing this inside a container and didn't
# want to install additional dependencies I am using command
# instead.
    - name: Create tftpboot directory
      file:
        path: /tftpboot/
        state: directory
        owner: nobody
        group: nogroup
 
    - name: Copy iPXE files to tftpboot
      copy:
        src: "{{ item }}"
        dest: /tftpboot/
        owner: nobody
        group: nogroup
        mode: 0700 
      with_items: ipxe_files
      
    - name: Dependency to build iPXE
      command: apt-get -y install {{ item }}
      with_items: pkgs

    - name: Create pxelinux.cfg directory
      file:
        path: /tftpboot/pxelinux.cfg/
        state: directory
        owner: nobody
        group: nogroup
    
    - name: Copy syslinux files to tftpboot
      copy:
        src: "{{ item }}"
        dest: /tftpboot/
        owner: nobody
        group: nogroup
        mode: 0700
      with_items: syslinux_files
